### PR TITLE
Add SecurityProblemKind::SecurityShields

### PR DESCRIPTION
**Pull request by matiasbzurovski**

### CODE REVIEW

**Review by Sajjon — COMMENTED** [review]
Lgtm 

Feel free to merge if you can

**Comment by Sajjon** [comment]
Lgtm, feel free to merge if you can

**Comment by matiasbzurovski** [comment]
@Sajjon need 1 approval :)

**Comment by Sajjon** [comment]
Why I said "if you can" (bypass check). Else will approve from work phone in ~5min. Dont have it on my atm

**Review by CyonAlexRDX — APPROVED** [review]
LGTM

**Pull request merged**
