### PR TITLE
Implement device info serde in Kotlin

### PR DESCRIPTION
**Pull request by micbakos-rdx**
This PR also exports in Sargon the `DeviceDescription` (previously known as DeviceInfo on Android).

### CODE REVIEW

**Review by sergiupuhalschi-rdx — APPROVED** [review]
LGTM

**Review by CyonAlexRDX — APPROVED** [review]
LGTM

**Comment by CyonAlexRDX** [comment]
Bump
Version ?

**Comment by micbakos-rdx** [comment]
> Bump Version ?

Will do but first I would like to sync with you before I do any more commits into this one.

**Comment by micbakos-rdx** [comment]
After discussing with @CyonAlexRDX I am going to close this PR in favor of the current structure we have on Android which preserves the model and the name of the device.

**Pull request closed without merging**
